FmtsProj/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FmtsEntity;
using FmtsServices.Model;
using FmtsServices;

namespace FmtsProj.Controllers
{
    public class PermissionsController : ControllerBase
    {
        private BMOSContext db = new BMOSContext();

        
        [SessionExpireFilter]
        public ActionResult AllPermissions()
        {
            PermissionService permissionService = new PermissionService();
            var list = permissionService.GetGroupsModelList();
            return PartialView("_Permissions", list);
        }
        
    }
}

FmtsProj/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FmtsEntity;
using FmtsServices;
using FmtsServices.Model;

namespace FmtsProj.Controllers
{
    public class RolesController : ControllerBase
    {
        // GET: Roles
        public ActionResult Index()
        {
            return View();
        }


        // GET: Roles/Create
        public ActionResult Create()
        {
            RoleModel model = new RoleModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public ActionResult Create(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                RolesService rolesService = new RolesService();
                role.ByUserID = CurrentUser.UserID;
                rolesService.SaveRole(role);
                return RedirectToAction("Index");
            }
            return View(role);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RolesService rolesService = new RolesService();
            var model = rolesService.FindByID(id.GetValueOrDefault());
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public ActionResult Edit(RoleModel model)
        {
            if (ModelState.IsValid)
            {
                RolesService rolesService = new RolesService();
                model.ByUserID = CurrentUser.UserID;
                rolesService.UpdateRole(model);

                return RedirectToAction("Index");
            }
            return View(model);
        }


        public ActionResult FindRolesGrid(RoleFilterModel model)
        {
            RolesService rolesService = new RolesService();
            int count = 0;

            var list = rolesService.FindRoles(model, out count);
            return Json(new { data = list, itemsCount = count }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateRole(RoleModel roleModel)
        {
            RolesService roleService = new RolesService();
            roleModel.ByUserID = CurrentUser.UserID;
            roleService.UpdateRole(roleModel);

            var driver = roleService.FindByID(roleModel.RoleID);
            return Json(new { driver = driver }, JsonRequestBehavior.AllowGet);
        }

        [SessionExpireFilter]
        public ActionResult DeleteRole(int roleId)
        {
            RolesService roleService = new RolesService();
            roleService.DeleteRole(roleId, CurrentUser.UserID);
            return Json("Done", JsonRequestBehavior.AllowGet);
        }

        [SessionExpireFilter]
        public ActionResult GetRolePermissions(int roleId)
        {
            PermissionService permissionService = new PermissionService();
            var list = permissionService.GetByRoleID(roleId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        [SessionExpireFilter]
        public ActionResult SaveRolePermissions(int roleId, string permissionIds)
        {
            PermissionService permissionService = new PermissionService();
            permissionService.UpdateRolePermissions(roleId, permissionIds, CurrentUser.UserID);
            return Json("", JsonRequestBehavior.AllowGet);
        }
        

    }
}

FmtsProj/Views/Roles/Create.cshtml
@model FmtsServices.Model.RoleModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Main_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        @Html.Partial("_CreateEdit", @Model)

    </div>
}

FmtsProj/Views/Roles/Edit.cshtml
@model FmtsServices.Model.RoleModel

@{
    Layout = "~/Views/Shared/Main_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.RoleID)

        @Html.Partial("_CreateEdit", @Model)


    </div>
}

FmtsProj/Views/Roles/Index.cshtml
@using FmtsProj.Common
@using FmtsServices.Model

@{
    //ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Main_Layout.cshtml";
}

<script type="text/javascript">
    var haspermissiontoEdit = @Common.HasPermissions(Enums.PermissionsEnum.VehiclesEdit).ToString().ToLower();
</script>
<link rel="stylesheet" href=@Url.Content("/Content/css/font-awesome.min.css")>
<script type="text/javascript" src=@Url.Content("/Content/js/jquery-3.2.1.min.js")></script>
<script type="text/javascript" src=@Url.Content("/Content/js/jsgrid.min.js")></script>
<script type="text/javascript" src=@Url.Content("/Content/js/jquery-ui.min.js")></script>
<div class="col-md-12">
    <div class="card">
        @if (Common.HasPermissions(Enums.PermissionsEnum.VehiclesCreate))
        {
            <div class="header margin-bottom-35">
                <div class="col-sm-3 ">
                    <button type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Create", "Roles")'">New</button>
                </div>
            </div>
        }
        <div class="content" id="gridContent">
            <div id="jsGrid"></div>
        </div>
    </div>
</div>

<div id="editPermissionsModal" title="Role Permissions" style="overflow-x:hidden">
    <div style="margin-top:20px;margin-left:10px">
        <div class="row">
            <div style="width:570px">
                <div class="well" style="overflow: auto;">
                    
                    @*<ul id="check-list-box" class="list-group checked-list-box">*@

                        @Html.Action("AllPermissions", "Permissions")

                        @*<li class="list-group-item">Cras justo odio</li>
                        <li class="list-group-item" data-color="success">Dapibus ac facilisis in</li>
                        <li class="list-group-item" data-color="info">Morbi leo risus</li>
                        <li class="list-group-item" data-color="warning">Porta ac consectetur ac</li>
                        <li class="list-group-item" data-color="danger">Vestibulum at eros</li>*@
                    @*</ul>*@
                    <div id="loaderOverall" class="lock_page_div">
                        <div class="centered">
                            <img src=@Url.Content("/Content/images/load.gif") alt="Alternate Text" width="60" />
                        </div>
                    </div>
                    <br />
                    <button class="btn btn-primary col-xs-6" id="btnPermissionsSave">Save</button>
                    <button class="btn btn-primary col-xs-6" id="btnPermissionsClose">Close</button>
                </div>
            </div>
        </div>
        
    </div>
</div>

<style>
    .state-icon {
        left: -5px;
    }
    .list-group-item-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(66, 139, 202);
    }
    .well .list-group {
        margin-bottom: 0px;
    }
    .lock_page_div {
        position: absolute;
        top: 0;
        left: 0;
        z-index: 9999;
        width: 100%;
        height: 100%;
        display: none;
        background: rgba(0,0,0,0.3);
    }
    .centered {
  position: fixed;
  top: 50%;
  left: 50%;
  margin-top: -50px;
  margin-left: -100px;
}
</style>

<script type="text/javascript" src=@Url.Content("/Content/js/Roles/permissions.js?v=1.00")></script>
<script type="text/javascript" src=@Url.Content("/Content/js/Roles/index.js?v=1.00")></script>

FmtsProj/Views/Roles/_CreateEdit.cshtml
@model FmtsServices.Model.RoleModel


@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(model => model.RoleName, htmlAttributes: new { @class = "control-label left-label col-md-2" })
    <div class="col-md-9">
        @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.RoleName, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label left-label col-md-2" })
    <div class="col-md-9">
        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
    </div>
</div>


<div class="form-group">
    <div class=" left-label col-md-2">
    </div>
    <div class="col-md-9">
        <input type="submit" value="Save" class="btn btn-primary btn-lg" />
        <button type="button" class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Index")'">Back</button>
    </div>
</div>